dist: xenial

language: go
go: 1.15.x

services:
  - docker

script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash .ci/check_for_changelog_in_diff.sh; fi
  - .ci/run_and_validate_e2e_tests.sh
